name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: DigitalOcean Docker Image Publish
      uses: ripplr-io/docr-docker-publish@v1
      with:
        image_path: registry.digitalocean.com/pretux/pretux-bot:$(date +%s)
        docker_build_context: .
